import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-bnpl-merchant-settlement-reconciliation",
  "engine": "recovery",
  "title": "BNPL Merchant Settlement Reconciliation",
  "shortTitle": "BNPL Merchant Settlement Reconciliation",
  "tagline": "Reconcile buy-now-pay-later orders, fees, returns, and promotional subsidies to merchant settlement entitlement.",
  "industry": "Alternative Payments Finance",
  "buyer": "Retailers and ecommerce merchants",
  "uiPort": 4669,
  "apiPort": 5669,
  "accent": "#c2410c",
  "currency": "USD",
  "primaryOutcome": "BNPL Merchant Settlement Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect provider agreements, orders, installments, captures, cancellations, returns, merchant discount rates, promotions, disputes, settlements, and deposits in one accountable workflow. Reconcile buy-now-pay-later orders, fees, returns, and promotional subsidies to merchant settlement entitlement.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "BNPL Merchant Settlement Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("provider-agreement-library","BMS01","Provider agreement library","Execute provider agreement library using provider agreements, orders, installments, captures, cancellations, returns, merchant discount rates, promotions, disputes, settlements, and deposits.","Produce a governed provider agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","BNPL Provider / Merchant Channel","text","BNPL Provider / Merchant Channel · Standard Case"],["caseReference","Provider agreement library Reference","text","BMS01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",865000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1046650],["domainDriver","Transaction State","select","Completed",["Completed","Returned","Partially refunded"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider agreement library case","Order installment ingestion case","Capture completion matching case","Cancellation control case","Full return reconciliation case"]}),
feature("order-installment-ingestion","BMS02","Order installment ingestion","Execute order installment ingestion using provider agreements, orders, installments, captures, cancellations, returns, merchant discount rates, promotions, disputes, settlements, and deposits.","Produce a governed order installment ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","BNPL Provider / Merchant Channel","text","BNPL Provider / Merchant Channel · Standard Case"],["caseReference","Order installment ingestion Reference","text","BMS02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",865000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1046650],["domainDriver","Transaction State","select","Completed",["Completed","Returned","Partially refunded"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider agreement library case","Order installment ingestion case","Capture completion matching case","Cancellation control case","Full return reconciliation case"]}),
feature("capture-completion-matching","BMS03","Capture completion matching","Execute capture completion matching using provider agreements, orders, installments, captures, cancellations, returns, merchant discount rates, promotions, disputes, settlements, and deposits.","Produce a governed capture completion matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","BNPL Provider / Merchant Channel","text","BNPL Provider / Merchant Channel · Standard Case"],["caseReference","Capture completion matching Reference","text","BMS03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",865000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1046650],["domainDriver","Transaction State","select","Completed",["Completed","Returned","Partially refunded"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider agreement library case","Order installment ingestion case","Capture completion matching case","Cancellation control case","Full return reconciliation case"]}),
feature("cancellation-control","BMS04","Cancellation control","Execute cancellation control using provider agreements, orders, installments, captures, cancellations, returns, merchant discount rates, promotions, disputes, settlements, and deposits.","Produce a governed cancellation control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","BNPL Provider / Merchant Channel","text","BNPL Provider / Merchant Channel · Standard Case"],["caseReference","Cancellation control Reference","text","BMS04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",865000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1046650],["domainDriver","Transaction State","select","Completed",["Completed","Returned","Partially refunded"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider agreement library case","Order installment ingestion case","Capture completion matching case","Cancellation control case","Full return reconciliation case"]}),
feature("full-return-reconciliation","BMS05","Full return reconciliation","Execute full return reconciliation using provider agreements, orders, installments, captures, cancellations, returns, merchant discount rates, promotions, disputes, settlements, and deposits.","Produce a governed full return reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","BNPL Provider / Merchant Channel","text","BNPL Provider / Merchant Channel · Standard Case"],["caseReference","Full return reconciliation Reference","text","BMS05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",865000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1046650],["domainDriver","Transaction State","select","Completed",["Completed","Returned","Partially refunded"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider agreement library case","Order installment ingestion case","Capture completion matching case","Cancellation control case","Full return reconciliation case"]}),
feature("partial-return-allocation","BMS06","Partial return allocation","Execute partial return allocation using provider agreements, orders, installments, captures, cancellations, returns, merchant discount rates, promotions, disputes, settlements, and deposits.","Produce a governed partial return allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","BNPL Provider / Merchant Channel","text","BNPL Provider / Merchant Channel · Standard Case"],["caseReference","Partial return allocation Reference","text","BMS06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",865000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1046650],["domainDriver","Transaction State","select","Completed",["Completed","Returned","Partially refunded"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider agreement library case","Order installment ingestion case","Capture completion matching case","Cancellation control case","Full return reconciliation case"]}),
feature("merchant-discount-calculation","BMS07","Merchant discount calculation","Execute merchant discount calculation using provider agreements, orders, installments, captures, cancellations, returns, merchant discount rates, promotions, disputes, settlements, and deposits.","Produce a governed merchant discount calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","BNPL Provider / Merchant Channel","text","BNPL Provider / Merchant Channel · Standard Case"],["caseReference","Merchant discount calculation Reference","text","BMS07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",865000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1046650],["domainDriver","Transaction State","select","Completed",["Completed","Returned","Partially refunded"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider agreement library case","Order installment ingestion case","Capture completion matching case","Cancellation control case","Full return reconciliation case"]}),
feature("promotional-subsidy-calculation","BMS08","Promotional subsidy calculation","Execute promotional subsidy calculation using provider agreements, orders, installments, captures, cancellations, returns, merchant discount rates, promotions, disputes, settlements, and deposits.","Produce a governed promotional subsidy calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","BNPL Provider / Merchant Channel","text","BNPL Provider / Merchant Channel · Standard Case"],["caseReference","Promotional subsidy calculation Reference","text","BMS08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",865000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1046650],["domainDriver","Transaction State","select","Completed",["Completed","Returned","Partially refunded"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider agreement library case","Order installment ingestion case","Capture completion matching case","Cancellation control case","Full return reconciliation case"]}),
feature("consumer-dispute-allocation","BMS09","Consumer dispute allocation","Execute consumer dispute allocation using provider agreements, orders, installments, captures, cancellations, returns, merchant discount rates, promotions, disputes, settlements, and deposits.","Produce a governed consumer dispute allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","BNPL Provider / Merchant Channel","text","BNPL Provider / Merchant Channel · Standard Case"],["caseReference","Consumer dispute allocation Reference","text","BMS09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",865000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1046650],["domainDriver","Transaction State","select","Completed",["Completed","Returned","Partially refunded"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider agreement library case","Order installment ingestion case","Capture completion matching case","Cancellation control case","Full return reconciliation case"]}),
feature("reserve-hold-validation","BMS10","Reserve hold validation","Execute reserve hold validation using provider agreements, orders, installments, captures, cancellations, returns, merchant discount rates, promotions, disputes, settlements, and deposits.","Produce a governed reserve hold validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","BNPL Provider / Merchant Channel","text","BNPL Provider / Merchant Channel · Standard Case"],["caseReference","Reserve hold validation Reference","text","BMS10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",865000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1046650],["domainDriver","Transaction State","select","Completed",["Completed","Returned","Partially refunded"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider agreement library case","Order installment ingestion case","Capture completion matching case","Cancellation control case","Full return reconciliation case"]}),
feature("settlement-statement-matching","BMS11","Settlement statement matching","Execute settlement statement matching using provider agreements, orders, installments, captures, cancellations, returns, merchant discount rates, promotions, disputes, settlements, and deposits.","Produce a governed settlement statement matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","BNPL Provider / Merchant Channel","text","BNPL Provider / Merchant Channel · Standard Case"],["caseReference","Settlement statement matching Reference","text","BMS11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",865000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1046650],["domainDriver","Transaction State","select","Completed",["Completed","Returned","Partially refunded"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider agreement library case","Order installment ingestion case","Capture completion matching case","Cancellation control case","Full return reconciliation case"]}),
feature("missing-deposit-detection","BMS12","Missing deposit detection","Execute missing deposit detection using provider agreements, orders, installments, captures, cancellations, returns, merchant discount rates, promotions, disputes, settlements, and deposits.","Produce a governed missing deposit detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","BNPL Provider / Merchant Channel","text","BNPL Provider / Merchant Channel · Standard Case"],["caseReference","Missing deposit detection Reference","text","BMS12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",865000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1046650],["domainDriver","Transaction State","select","Completed",["Completed","Returned","Partially refunded"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider agreement library case","Order installment ingestion case","Capture completion matching case","Cancellation control case","Full return reconciliation case"]}),
feature("provider-correction-workflow","BMS13","Provider correction workflow","Execute provider correction workflow using provider agreements, orders, installments, captures, cancellations, returns, merchant discount rates, promotions, disputes, settlements, and deposits.","Produce a governed provider correction workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","BNPL Provider / Merchant Channel","text","BNPL Provider / Merchant Channel · Standard Case"],["caseReference","Provider correction workflow Reference","text","BMS13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",865000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1046650],["domainDriver","Transaction State","select","Completed",["Completed","Returned","Partially refunded"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider agreement library case","Order installment ingestion case","Capture completion matching case","Cancellation control case","Full return reconciliation case"]}),
feature("cash-reconciliation","BMS14","Cash reconciliation","Execute cash reconciliation using provider agreements, orders, installments, captures, cancellations, returns, merchant discount rates, promotions, disputes, settlements, and deposits.","Produce a governed cash reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","BNPL Provider / Merchant Channel","text","BNPL Provider / Merchant Channel · Standard Case"],["caseReference","Cash reconciliation Reference","text","BMS14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",865000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1046650],["domainDriver","Transaction State","select","Completed",["Completed","Returned","Partially refunded"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider agreement library case","Order installment ingestion case","Capture completion matching case","Cancellation control case","Full return reconciliation case"]}),
feature("provider-channel-analytics","BMS15","Provider channel analytics","Execute provider channel analytics using provider agreements, orders, installments, captures, cancellations, returns, merchant discount rates, promotions, disputes, settlements, and deposits.","Produce a governed provider channel analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","BNPL Provider / Merchant Channel","text","BNPL Provider / Merchant Channel · Standard Case"],["caseReference","Provider channel analytics Reference","text","BMS15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",865000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1046650],["domainDriver","Transaction State","select","Completed",["Completed","Returned","Partially refunded"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider agreement library case","Order installment ingestion case","Capture completion matching case","Cancellation control case","Full return reconciliation case"]})
]);
